import Link from "next/link";
import { MarketingFooter } from "@/components/MarketingFooter";
import { MarketingNav } from "@/components/MarketingNav";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <header className="sticky top-0 z-50 bg-white border-b border-slate-200">
        <MarketingNav />
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <h1 className="text-3xl sm:text-4xl font-bold mb-6">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last updated: March 9, 2026</p>

        <div className="prose prose-slate max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing or using Credit 800 (&quot;the Service&quot;), operated by Credit 800 LLC, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Credit 800 is a free automated financial platform including:
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4 mb-3">
              <li>
                Automated credit report analysis and FCRA-compliant dispute letter generation
              </li>
              <li>Credit score tracking, debt payoff planning, budget management, credit score simulator</li>
              <li>CFPB complaint generator, document vault, identity monitoring, credit builder product recommendations</li>
              <li>Optional physical USPS mailing of dispute letters ($2/letter)</li>
            </ul>
            <p className="text-slate-600 leading-relaxed">
              Credit 800 is free and available to all registered users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Limitations and Educational Use</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Credit 800 provides educational tools and letter templates. Credit 800:
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>Does not guarantee removal of any items from your credit report</li>
              <li>Does not promise to improve your credit score by any specific amount</li>
              <li>Does not submit disputes on your behalf or act as your agent</li>
              <li>Does not provide legal advice</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              You are solely responsible for reviewing, editing, and submitting any dispute letters generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Billing</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Credit 800 is free for all registered users.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>USPS physical mailing of dispute letters incurs a $2 per letter charge at time of mailing</li>
              <li>Payments are processed securely by Stripe. Credit 800 does not store your payment card information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Account Security and Two-Factor Authentication</h2>
            <p className="text-slate-600 leading-relaxed">
              Two-factor authentication (2FA) via email is mandatory for all accounts and cannot be disabled.
              A one-time verification code is sent to your registered email address each time you log in.
              You are responsible for maintaining the security of your email account. Codes are valid for a
              limited time, hashed with SHA-256 before storage, and automatically invalidated after use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. User Responsibilities</h2>
            <p className="text-slate-600 leading-relaxed mb-3">You agree to:</p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>Provide accurate information when creating your account and using the Service</li>
              <li>Only upload credit reports that belong to you</li>
              <li>Review all generated content before use (Self Service plan)</li>
              <li>Not rely solely on the Service for credit-related decisions</li>
              <li>Comply with all applicable laws when submitting disputes</li>
              <li>Not use the Service to file false or fraudulent disputes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Automated Content Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">
              The Service uses automated technology to analyze credit reports and generate dispute letters.
              Generated content may contain errors or inaccuracies and may not be appropriate for your specific
              situation. You should always review, verify, and customize any generated content before use.
              Credit 800 is not responsible for any consequences resulting from the use of generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Credit Builder Product Recommendations</h2>
            <p className="text-slate-600 leading-relaxed">
              The Service may display curated secured credit cards, credit-builder loans, and similar financial
              products. Credit 800 may receive referral compensation if you apply for or open an account with a
              featured provider. Product listings are provided for informational purposes only and do not constitute
              financial advice. Always review the full terms of any financial product before applying. Credit 800 is
              not responsible for the terms, availability, or accuracy of third-party product offerings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Privacy and Data Security</h2>
            <p className="text-slate-600 leading-relaxed">
              Your use of the Service is also governed by our <Link href="/privacy" className="text-teal-600 hover:text-teal-500">Privacy Policy</Link>.
              We take reasonable measures to protect your personal information, but no method of transmission
              over the Internet is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CREDIT 800 SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
              WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
              INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Modifications to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to modify these Terms of Service at any time. We will notify users of
              any material changes by email or by posting the updated terms on the Service. Your continued
              use of the Service after such changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms are governed by the laws of the United States. Any disputes arising from these
              Terms or your use of the Service shall be resolved through binding arbitration, except where
              prohibited by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Contact Information</h2>
            <p className="text-slate-600 leading-relaxed">
              If you have any questions about these Terms of Service, please <a href="/support" className="text-teal-600 hover:text-teal-500">contact us here</a>.
            </p>
          </section>
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
