import Link from "next/link";
import { MarketingFooter } from "@/components/MarketingFooter";
import { MarketingNav } from "@/components/MarketingNav";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <header className="sticky top-0 z-50 bg-white border-b border-slate-200">
        <MarketingNav />
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <h1 className="text-3xl sm:text-4xl font-bold mb-6">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last updated: June 1, 2026</p>

        <div className="prose prose-slate max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing or using Credit 800 (&quot;the Service&quot;), operated by Credit 800 LLC, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Credit 800 offers two plans:
            </p>
            <p className="text-slate-600 font-medium mb-1">Self Service (Free)</p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4 mb-4">
              <li>Automated credit report analysis and FCRA-compliant dispute letter generation</li>
              <li>Credit score tracking, debt payoff planning, budget management, credit score simulator</li>
              <li>CFPB complaint generator, document vault, identity monitoring, credit builder product recommendations</li>
              <li>Optional physical USPS mailing of dispute letters ($2/letter)</li>
            </ul>
            <p className="text-slate-600 font-medium mb-1">Autopilot ($49/month)</p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4 mb-3">
              <li>Everything in Self Service</li>
              <li>Monthly soft-pull credit report retrieval on your behalf</li>
              <li>Automatic generation and USPS mailing of dispute letters (up to 10/month)</li>
              <li>Hands-free VantageScore tracking and FCRA-compliant full automation</li>
              <li>Compliance audit trail and priority support</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Limitations and Disclaimers</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Regardless of plan, Credit 800:
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>Does not guarantee removal of any items from your credit report</li>
              <li>Does not promise to improve your credit score by any specific amount</li>
              <li>Does not provide legal advice</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              <strong>Self Service users</strong> are solely responsible for reviewing, editing, and submitting any dispute letters generated by the Service.
            </p>
            <p className="text-slate-600 leading-relaxed mt-3">
              <strong>Autopilot users</strong> authorize Credit 800 to pull their credit report and submit dispute letters on their behalf under FCRA § 604(a)(2). By activating Autopilot, you provide written authorization for these actions. You may revoke this authorization at any time by canceling your Autopilot subscription or contacting support.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Billing</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Credit 800 offers a free Self Service plan and a paid Autopilot plan.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>Self Service is free. Optional USPS physical mailing of dispute letters incurs a $2 per letter charge at time of mailing</li>
              <li>Autopilot is $49/month, billed monthly. Autopilot includes automatic USPS mailing of up to 10 dispute letters per month at no additional per-letter charge</li>
              <li>Autopilot subscriptions renew automatically each month until canceled. You may cancel at any time from your profile or by contacting support</li>
              <li>Payments are processed securely by Stripe. Credit 800 does not store your full payment card information</li>
              <li>Refunds are not provided for partial billing periods</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Account Security</h2>
            <p className="text-slate-600 leading-relaxed">
              You are responsible for maintaining the security of your account credentials. Do not share your
              password with anyone. Credit 800 uses industry-standard encryption and security practices to protect
              your account. You agree to notify us immediately of any unauthorized access to your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. User Responsibilities</h2>
            <p className="text-slate-600 leading-relaxed mb-3">You agree to:</p>
            <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
              <li>Provide accurate information when creating your account and using the Service</li>
              <li>Only upload credit reports that belong to you</li>
              <li>Review all generated content before use (Self Service plan)</li>
              <li>Not rely solely on the Service for credit-related decisions</li>
              <li>Comply with all applicable laws when submitting disputes</li>
              <li>Not use the Service to file false or fraudulent disputes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Automated Content Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">
              The Service uses automated technology to analyze credit reports and generate dispute letters.
              Generated content may contain errors or inaccuracies and may not be appropriate for your specific
              situation. You should always review, verify, and customize any generated content before use.
              Credit 800 is not responsible for any consequences resulting from the use of generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Privacy and Data Security</h2>
            <p className="text-slate-600 leading-relaxed">
              Your use of the Service is also governed by our <Link href="/privacy" className="text-teal-600 hover:text-teal-500">Privacy Policy</Link>.
              We take reasonable measures to protect your personal information, but no method of transmission
              over the Internet is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CREDIT 800 SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
              WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
              INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Modifications to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to modify these Terms of Service at any time. We will notify users of
              any material changes by email or by posting the updated terms on the Service. Your continued
              use of the Service after such changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms are governed by the laws of the United States. Any disputes arising from these
              Terms or your use of the Service shall be resolved through binding arbitration, except where
              prohibited by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Contact Information</h2>
            <p className="text-slate-600 leading-relaxed">
              If you have any questions about these Terms of Service, please <a href="/support" className="text-teal-600 hover:text-teal-500">contact us here</a>.
            </p>
          </section>
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
